//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmrcTpvsProxy.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CascadeEdgeCaseFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CascadeEdgeCaseFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HmrcTpvsProxy.Domain.CascadeEdgeCaseFiles", typeof(CascadeEdgeCaseFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;AR&lt;/DataTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ARData {
            get {
                return ResourceManager.GetString("ARData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;env:Body&gt;&lt;ns:DPSrequestTokenResponse xmlns:ns=&quot;https://tpvs.hmrc.gov.uk/dpsauthentication&quot;&gt;&lt;ns:DPSrequestTokenResult&gt;&amp;lt;![CDATA[&amp;lt;saml:Assertion xmlns:saml=&quot;urn:oasis:names:tc:SAML:1.0:assertion&quot; xmlns=&quot;urn:oasis:names:tc:SAML:1.0:assertion&quot; xmlns:samlp=&quot;urn:oasis:names:tc:SAML:1.0: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Authorisation {
            get {
                return ResourceManager.GetString("Authorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;NOT&lt;/DataT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NOTData {
            get {
                return ResourceManager.GetString("NOTData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;RTI&lt;/DataT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NVRData {
            get {
                return ResourceManager.GetString("NVRData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;P6&lt;/DataTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P6Data {
            get {
                return ResourceManager.GetString("P6Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;P9&lt;/DataTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P9Data {
            get {
                return ResourceManager.GetString("P9Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;SL1&lt;/DataT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SL1Data {
            get {
                return ResourceManager.GetString("SL1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;env:Body&gt;
        ///		&lt;DPSretrieveResponse xmlns=&quot;https://tpvs.hmrc.gov.uk/dps&quot;&gt;
        ///			&lt;DPSdata xmlns=&quot;http://www.govtalk.gov.uk/taxation/DPSwrapper/1&quot;&gt;
        ///				&lt;DPSheader&gt;
        ///					&lt;Service&gt;PAYE&lt;/Service&gt;
        ///					&lt;EntityType&gt;EmpRef&lt;/EntityType&gt;
        ///					&lt;Entity&gt;123/A6&lt;/Entity&gt;
        ///					&lt;DataType&gt;SL2&lt;/DataT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SL2Data {
            get {
                return ResourceManager.GetString("SL2Data", resourceCulture);
            }
        }
    }
}
